---
title: "Graphs_on_Maps"
author: "Shweta Purushe"
date: "6/13/2018"
output: html_document
---

```{r}
suppressPackageStartupMessages(library(dplyr))
#suppressPackageStartupMessages(library(ggmap))geocode("Kashmir", output = "latlon", source="google")
suppressPackageStartupMessages(library(igraph))
suppressPackageStartupMessages(library(ggplot2))
library(maptools)
```

```{r}
edges <- read.csv("/Users/spurushe/Downloads/edges_for_plot.csv");
head(edges)
```

```{r}
regions <- read.csv("/Users/spurushe/Downloads/nodes.csv")
names(regions) <- c("id", "name", "lon", "lat")
regions
```

```{r}
e <- edges%>%select(c("from", "to","Beta_diversity", "Latitude_from","Longitude_from", "Latitude_to", "Longitude_to"))
e <- rename(e,x = "Longitude_from", y= "Latitude_from", xend = "Longitude_to", yend = "Latitude_to");

#should be the same at next structure
# edges_for_plot <- e %>%
#   inner_join(regions %>% select(id, lon, lat), by = c('from' = 'id')) %>%
#   rename(x = lon, y = lat) %>%
#   inner_join(regions %>% select(id, lon, lat), by = c('to' = 'id')) %>%
#   rename(xend = lon, yend = lat)
nrow(e) == nrow(edges)

e2 <- e[2:16, ]
```

```{r}
g <- graph_from_data_frame(e2, directed = TRUE, vertices = regions)

```

```{r}
regions$weight = degree(g)
```

```{r}
#Map theme 
maptheme <- theme(panel.grid = element_blank()) +
  theme(axis.text = element_blank()) +
  theme(axis.ticks = element_blank()) +
  theme(axis.title = element_blank()) +
  theme(legend.position = "bottom") +
  theme(panel.grid = element_blank()) +
  theme(panel.background = element_rect(fill = "#596673")) +
  theme(plot.margin = unit(c(0, 0, 0.5, 0), 'cm'))
```

```{r}
# getting the data from map_data World 

# fixed ratio coordinate system and setting lat long limits
country_shapes <- geom_polygon(aes(x = long, y = lat, group = group),
                               data = map_data('world'),
                               fill = "#CECECE", color = "#515151",
                               size = 0.15)


```

```{r fig.width = 25, fig.height = 15}

mapcoords <- coord_fixed(xlim = c(50, 150), ylim = c(0,50))


ggplot(regions) + country_shapes +
  geom_curve(aes(x = x, y = y, xend = xend, yend = yend,     # draw edges as arcs
                 color = 'red', size = (1-Beta_diversity)*2),
             data = e2, curvature = 0.33,
             alpha = 0.5) +
  scale_size_continuous(guide = FALSE, range = c(0.5, 4)) + # scale for edge widths
  geom_point(aes(x = lon, y = lat),                          # draw nodes
             shape = 21, size = regions$weight*2, fill = 'white',
             color = 'black', stroke = 0.5) +
  geom_text(aes(x = lon, y = lat, label = name),             # draw text labels
            hjust = 0, nudge_x = 1, nudge_y = 4,
            size = 3, color = "black", fontface = "bold") +
  mapcoords + maptheme
```

```{r fig.width = 25, fig.height = 15}
##################### WITH SHAPE FILE AND GGPLOT##################### 
area <- readShapePoly(file.choose())
area.points <- fortify(area)


country_shapes2 <- geom_polygon(aes(x = long,
      y = lat,
      group = group),
    data = area.points,
    color = 'lightblue', size = 2,
    alpha = 0.1) 


ggplot(regions) + country_shapes2 + 
 labs(x = "Longitude",
   y = "Latitude") +
  geom_curve(aes(x = x, y = y, xend = xend, yend = yend,     # draw edges as arcs
                 color = 'red', size = (1-Beta_diversity)*2),
             data = e2, curvature = 0.33,
             alpha = 0.5) +
  scale_size_continuous(guide = FALSE, range = c(0.5, 4)) + # scale for edge widths
  geom_point(aes(x = lon, y = lat),                          # draw nodes
             shape = 21, size = regions$weight*5, fill = 'white',
             color = 'black', stroke = 0.5) +
  geom_text(aes(x = lon, y = lat, label = name),             # draw text labels
            hjust = 0, nudge_x = 1, nudge_y = 4,
            size = 3, color = "lightblue", fontface = "bold") +
  mapcoords + maptheme
```


```{r fig.width=15}
# country_shapes <- geom_polygon(aes(x = long, y = lat, group = group),
#                                data = map_data('world'),
#                                fill = "#CECECE", color = "#515151",
#                                size = 0.15)

# mapImage <- get_googlemap(c(lon=89.29, lat=29.84),
#                       zoom = 3,
#                       maptype = "terrain")

mapcoords <- coord_fixed(xlim = c(50, 150), ylim = c(0,40))

ggmap(mapImage) +
geom_polygon(aes(x = long,y = lat,group = group), data = area.points,color = 'gray27',size=1.5, alpha =  0.2) +labs(x = "Longitude",y = "Latitude") +
geom_curve(aes(x = x, y = y, xend = xend, yend = yend,     # draw edges as arcs
                 color = 'red', size = (1-Beta_diversity)*2),
             data = e2, curvature = 0.33,
             alpha = 0.5) +
scale_size_continuous(guide = FALSE, range = c(0.5, 4)) +  
geom_point(aes(x = lon, y = lat),                          # draw nodes
             shape = 21, size = regions$weight*2, fill = 'white',
             color = 'black', stroke = 0.5 , data=regions) + 
# geom_text(aes(x = lon, y = lat, label = name), data= regions,             # draw text labels
#             hjust = 0, nudge_x = 1, nudge_y = 1,
#             size = 10, color = "gray27", fontface = "bold") +
mapcoords + maptheme

```


